### ISSUE TITLE
[EPIC] Frontend bugs/features in documentation

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#1021]
Frontend issues related to docs

- [x] https://github.com/SigNoz/signoz-web/issues/571
- [x] https://github.com/SigNoz/signoz-web/issues/572
- [ ] https://github.com/SigNoz/signoz-web/issues/1020

**Comment by YounixM** [comment]
@sawhil : Please share the updates on this

**Comment by sawhil** [comment]
Handed the part 2 to @Calm-Rock (Chitransh).
