### ISSUE TITLE
Parent Issue - Docs structure improvement

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz.io#123]
- [ ] https://github.com/SigNoz/signoz.io/issues/120
- [ ] https://github.com/SigNoz/signoz.io/issues/119
- [ ] https://github.com/SigNoz/signoz.io/issues/122

Inspiration Posthog and Clickhouse docs

**Comment by pranay01** [comment]
This commit solves #119 
https://github.com/SigNoz/signoz.io/commit/bac800f45b7dd0d396faad4d4e7aa6cb831ae6ca
