### ISSUE TITLE
[EPIC] Have Docs for monitoring GCP services

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#342]
We have Docs for monitoring AWS and Azure services, we need docs for monitoring the following GCP services using OpenTelemetry and SigNoz (Cloud and Self-Host) :

- [x] Compute Engine
- [x] App Engine
- [x] Kubernetes Engine (GKE)
- [x] Cloud Functions
- [x] Virtual Private Cloud
- [x] Cloud Load Balancing
- [x] Cloud SQL
- [x] Cloud Storage
- [x] Cloud Run
- [x] Cloud Monitoring

We need to have docs for the three signals - Traces, Logs and Metrics. The below table tells you which signals are required for which services:

| GCP Service                 | Traces         | Metrics        | Logs          |
|-----------------------------|----------------|----------------|---------------|
| Compute Engine              | ✔️ Done       | ✔️ Done        | ✔️ Done       |
| Kubernetes Engine (GKE)     | ✔️ Done        | ✔️ Done        | ✔️ Done       |
| Cloud Load Balancing        | ✖️ Not required        | ✔️ Done        | ✔️ Done       |
| Virtual Private Cloud (VPC) | ✖️ Not required| ✔️ Done         | ✔️ Done      |
| Cloud SQL                   | ✖️ Not required| ✔️ Done        | ✔️ Done       |
| Cloud Functions             | ✔️ Done        | ✔️ Done        | ✔️ Done       |
| App Engine                  | ✔️ Done        | ✔️ Done       | ✔️ Done       |
| Cloud Run                   | ✔️ Done        | ✔️ Done        | ✔️ Done       |
| Cloud Monitoring            | ✖️ Not required| In Progress        | ✖️ Not required|
| Cloud Storage               | ✖️ Not required| ✔️ Done       | ✔️ Done       |

Done --> 24
PR Raised --> 0
In Progress --> 0
Not Started --> 0

Reference Docs:
-  [Azure Monitoring](https://signoz.io/docs/azure-monitoring/bootstrapping/)
- [AWS Monitoring](https://signoz.io/docs/ec2-monitoring/)

**Comment by pranay01** [comment]
@Calm-Rock Can add status of this each cell in the above grid 

Add status like - `Done`, `In progress`, `Not started`, `Not required`


-- | -- | -- | --
Compute Engine | ✔️ | ✔️ | ✔️
Kubernetes Engine (GKE) | ✔️ | ✔️ | ✔️
Cloud Load Balancing | ✔️ | ✔️ | ✔️
Virtual Private Cloud (VPC) | ✖️ | ✔️ | ✔️
Cloud SQL | ✖️ | ✔️ | ✔️
Cloud Functions | ✔️ | ✔️ | ✔️
App Engine | ✔️ | ✔️ | ✔️
Cloud Run | ✔️ | ✔️ | ✔️
Cloud Monitoring | ✖️ | ✔️ | ✖️
Cloud Storage | ✖️ | ✔️ | ✔️

**Comment by Calm-Rock** [comment]
Done @pranay01!

**Comment by pranay01** [comment]
> Done @pranay01!

Ok, please keep updating this as new docs get released

**Comment by pranay01** [comment]
@Calm-Rock Please keep updating the tracker above as docs are released. I see 17 PRs raised, but only 1 done. Please just focus on this from execution perspective

**Comment by Calm-Rock** [comment]
This is done!
